# Introduction {#intro}

The Fish Program at WDFW currently uses [iFormBuilder](https://www.zerionsoftware.com/iformbuilder/) as a platform for building and deploying mobile forms. Although there are numerous alternative mobile platforms, both commercial and open-source, among the benefits of iFormBuilder are an easy-to-use form building application, a robust system for syncing between forms and devices, and an excellent application programming interface (API). The [API](http://docs.iformbuilder.apiary.io/#) is particulary useful, as it allows us to automate many of the most burdensome aspects of building forms and managing data flows.

## API

One case where the API can avoid a great deal of pain is in constructing large filtered option lists. The prime example for spawning ground surveys are the drop-downs for survey start and stop points along a given stream. Lists with thousands of elements can be constructed and uploaded to the iFormBuilder cloud in seconds. The [iformr](https://github.com/arestrom/iformr) functions are a set of tools that allows for using R scripts to automate many of these types of tasks. Contact me if you need help with this.

## Profiles

Since the source code for book is hosted on a public website, I will not go into detail on purchasing or setting up devices, assigning AppleIDs, Google Play store accounts, or connecting to our iFormBuider account. The only prerequiste that needs to be stressed here is that you will want to get a separate iFormBuilder **Profile** set up for your workgroup. The main benefit is that it keeps your forms and option lists segregated from other groups, and makes it less likely you will lose data because someone accidentally edited your form...or deleted an option list. Contact me if you need help to get this set up.

## Useful tips

There is a great deal of information available at the iFormBuilder website for learning how to build forms. This includes an extensive list of videos. Unfortunately, that information is not always well organized. You can often get better results prefacing *iformbuilder* with a general search term, such as *iformbuilder parse location* than using iFormBuilder's help. That said, the [Customer Success Center](https://iformbuilder.zendesk.com/hc/en-us) is still a good place to start. If you have not already done so, watch the [Art of Form Building](https://www.zerionsoftware.com/recording/form-builder-101-may-2016/) video for an introduction to best practices. 

At some point you will need to write simple JavaScript code. This is especially important when you want to create conditional logic to hide or show a data element, validate data, or sum up a set of counts. My favorite site for help with JavaScript is [w3schools](https://iformbuilder.zendesk.com/hc/en-us). If you need to do something more complex, you will usually find someone has already written a function to accomplish exactly what you want. Try searching on [stackoverflow](https://stackoverflow.com/questions/tagged/javascript). A selection of various JavaScript functions that may come in handy are located in the appendix. 




