# Core fields

The sections below detail the core data fields that need to be present in any mobile form intended to be submitted to our corporate spawning ground database. 

## Survey ID

The **first element** in the parent form of any mobile form used for spawning ground surveys should be a **unique survey ID**. Although iFormBuilder has a widget titled *Unique ID* this is not a good choice for our purposes. Their *Unique ID* widget is merely a combination of a constant prefix and an integer value that increments each time you start filling out a new form. For example, D16-1, D16-2, etc. 

The reason that iFormBuilder's solution is not a good choice is that it may result in generating IDs that conflict over time. For example, if after a season of using a form you decide to amend the structure, retire the old form and deploy the new version, you may end up with identical IDs for different surveys unless you also make sure to edit the prefix to some value never previously used. An alternate scenario is that you may want to create dedicated forms for different type of surveys, such as for fall Chinook, or spring Steelhead. To enfore uniqueness statewide there would need to be coordination in assigning prefixes over WDFW districts and regions, otherwise new forms may start incrementing overlapping IDs.  

An even more important reason for adding a truely unique survey ID element to our forms is that it can then be used as a primary key in our corporate database. To that end what we need is a unique identifier that is (virtually) guaranteed to always be unique. The solution is to use a random uuid (universally unique ID). A version 4 uuid can be generated using the JavaScript code below. See the *Briguy37* answer at [Stackoverflow](https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript).  

```{javascript, eval = FALSE}
function generateUUID () { // Public Domain/MIT
    var d = new Date().getTime();
    if (typeof performance !== 'undefined' && typeof performance.now === 'function'){
        d += performance.now(); //use high-precision timer if available
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
        var r = (d + Math.random() * 16) % 16 | 0;
        d = Math.floor(d / 16);
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
}
```

Copy and paste the code block above directly into the JavaScript panel of your parent form. You can access the JavaScript panel by clicking on the curly braces icon:  

<span style="color:#89BD48; font-size: 1.9em;">{}</span> 

in the top right corner of the Forms page when using the online Form Builder application. Make sure you paste it into the JavaScript panel for your parent form. 

You then create a read-only element in you parent form by clicking on the *Read Only* widget in the left-hand pane. The name of the element should be **survey_uuid**. Enter **Unique survey ID** as the label. In the **Dynamic Value** box enter the following: 

```{javascript, eval = FALSE}
generateUUID() 
```

Leave the **Condition Value** set to **false**. That way it will be invisible to the surveyor. The survey_uuid element will generate a universally unique ID every time a form is initiated that will look something like: 

```
33b78489-7ad3-4482-9455-3988e05bfb28
```

There are 2^122^ possible combinations for a randomly generated version 4 uuid. In practical terms this means that if you generate one billion UUIDs every second for approximately 85 years, the probability that two identical uuids will be generated is still only 50%. See article at [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier). 

## Data source




